# ref. http://docs.travis-ci.com/user/languages/objective-c/

language: objective-c
osx_image: xcode8
xcode_workspace: CotEditor.xcworkspace
xcode_scheme:
  - CotEditor
  - CotEditor -AppStore
before_install:
  - gem install cocoapods
script: xcodebuild -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

# enable container-based infrastructure
sudo: false
cache: cocoapods
